class FaturamentoPage {

    editarEnderecoFaturamento(nome, sobrenome, empresa, pais, endereco, complemento, cidade, estado, cep, telefone, email, observacao) {
        cy.get('#billing_first_name')
        .click()
        .type(nome)
        cy.get('#billing_last_name')
        .click()
        .type(sobrenome)
        cy.get('#billing_company')
        .click()
        .type(empresa)
        cy.get('#select2-billing_country-container')
        .click()
        .type(pais)
        .get('[aria-selected="true"]')
        .click()
        cy.get('#billing_address_1')
        .click()
        .type(endereco)
        cy.get('#billing_address_2')
        .click()
        .type(complemento)
        cy.get('#billing_city')
        .click()
        .type(cidade)
        cy.get('#select2-billing_state-container')
        .click()
        .type(estado + '{enter}')
        cy.get('#billing_postcode')
        .click()
        .type(cep)
        cy.get('#billing_phone')
        .click()
        .type(telefone)
        cy.get('#billing_email')
        .click()
        .type(email)
        cy.get('#order_comments')
        .click()
        .type(observacao)
        cy.get('#payment_method_cod').click()
        cy.get('.wc_payment_method.payment_method_cod > .payment_box > p').contains('Pagar em dinheiro na entrega.')
        cy.get('#terms').click()
    }
}

export default new FaturamentoPage()